server:
  port: ${PORT:8082}
  servlet:
    contextPath: ${CONTEXT_PATH:/}
management:
  server:
    port: ${MANAGEMENT_PORT:8092}
sample:
  restservice:
    url: ${SAMPLE_REST_SERVICE_URL:http://localhost:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
