version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    ports:
      - "27017:27017"
  postgresdb:
    container_name: postgresdb
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4"
    ports:
      - "5431:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@db.com
      PGADMIN_DEFAULT_PASSWORD: pwd
  mongoadmin:
    container_name: mongoadmin
    image: "mongo-express"
    ports:
      - "27016:8081"
    links:
      - mongodb:mongo
    restart: always
