version: '3'
services:
  registry:
    container_name: registry
    build: 
      context: ../service-registry
    ports:
      - "8761:8761"
    networks:
      - frontend      
      - backend      
networks:
   frontend:
    driver: bridge
   backend:
    driver: bridge