version: '3'
services:
  registry:
    container_name: registry
    build: 
      context: ../service-registry
    ports:
      - "8761:8761"
    networks:
      - frontend      
      - backend      
  gateway:
    container_name: gateway
    build: 
      context: ../service-gateway
    ports:
      - "8080:8080"
      - "9080:9080"
    environment:
      EUREKA_SERVER_ADDRESS: http://registry:8761/eureka
    depends_on: 
      - registry
    networks:
      - frontend      
      - backend      
networks:
   frontend:
    driver: bridge
   backend:
    driver: bridge