version: '3'
services:
  sample-spring-web:
    container_name: sample-spring-web
    build: 
      context: ../sample-spring-web
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - frontend      
      - backend      
networks:
   frontend:
    driver: bridge
   backend:
    driver: bridge