version: '3'
services:
  sample-spring-web:
    container_name: sample-spring-web
    build: 
      context: ../sample-spring-web
    ports:
      - "8082:8082"
      - "9082:9082"
    environment:
      EUREKA_SERVER_ADDRESS: http://registry:8761/eureka
      CONTEXT_PATH: /sample-spring-web
      SAMPLE_REST_SERVICE_URL: http://gateway:8080/sample-rest-service
      AMQP_SERVER_ADDRESS: rabbitmq
      AMQP_SERVER_PORT: 5672
      AMQP_SERVER_USERNAME: guest
      AMQP_SERVER_PASSWORD: guest
    networks:
      - frontend      
      - backend      
networks:
   frontend:
    driver: bridge
   backend:
    driver: bridge